file_path = 'MauiLearningPlatform/Components/Course/Chapter01.razor'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

import re

# Find pre tags that contain "code-toolbar" or "toolbar" or "button" inside them?
# Actually, the structure seems to be:
# <div class="code-toolbar"><pre ...> ... <div class="toolbar">...</div> ... </pre></div>
# We want:
# <div class="code-toolbar"><pre ...> ... </pre><div class="toolbar">...</div></div>

# But wait, inspect_div.py showed:
# ... </div></button><pre ...
# This implies a NEW pre starts after the button.
# So maybe:
# <pre ...> ... <button ...> ... </button><pre ...> ... </pre> ... </pre>
# This is very messed up.

# Let's look at the specific location 19970.
# We know pre starts there.
# We know button is at 20040.
# Let's see what's between them.
start = 19970
end = 20100
print(f"Content {start}-{end}: {content[start:end]}")

# It seems the "toolbar" is injected at the TOP of the pre?
# Or maybe the pre tag is NOT closed, and the next pre tag starts?
# And the toolbar is in between?
# <pre ...> ... (no close) <div class="toolbar">...</div> <pre ...>
# This would explain Unclosed pre.

# I'll try to find where the "toolbar" starts.
# It usually starts with <div class="toolbar"> or <div class="code-toolbar"> (if nested).
# But here it seems to be just <button>?
# inspect_div.py showed: ... <div class="copy-icon"></div></button><pre ...
# So <button> ends. Then <pre> starts.
# Where did <button> start?
# I'll search backwards from 20040 for <button.

idx = content.rfind('<button', 0, 20040)
print(f"Button starts at: {idx}")
print(f"Context around button start: {content[idx-50:idx+50]}")

# If button is inside pre.
# We should close pre before button?
# But pre content (code) should be inside pre.
# If button is the copy button, it should be OUTSIDE pre (in toolbar).
# So: </pre><div class="toolbar"><button ...>...</button></div>
# But we need to know where the code ENDS.
# If the code is `<?xml ...`.
# And button is BEFORE `<?xml ...`?
# inspect_div.py: `... </button><pre class="language-xml" ... <code><span class="token prolog">&lt;?xml ...`
# So the button is BEFORE the code?
# And BEFORE the `pre` that contains the code?
# But `inspect_pre.py` showed `pre` at 19970.
# And `inspect_div.py` showed `pre` AFTER button.
# So:
# 19970: <pre ...> (Empty? or contains button?)
# ... button ...
# ... <pre ...> (The real code pre)
# This implies the first pre is wrapping the button and the second pre?
# <pre ...> <button ...> </button> <pre ...> ... </pre> </pre>
# This is definitely wrong.

# I should remove the outer pre?
# Or close it immediately?
# If the outer pre is `<pre class="line-numbers language-xml" copy-code-registered="">`.
# And the inner pre is `<pre class="language-xml" ...>`.
# It seems we have duplicate pre wrappers.
# One from the markdown conversion (maybe) and one from Prism/JS injection?
# But this is static content.

# I will try to remove the OUTER pre start tag.
# And the corresponding OUTER pre end tag?
# If I remove `<pre class="line-numbers language-xml" copy-code-registered="">` at 19970.
# Then I have `<code>...`? No.
# The context at 19970 was: `<div class="code-toolbar"><pre ...><code>...`
# Wait, `inspect_pre.py` showed `<code>` immediately after `pre`.
# `... <pre ...><code><span class="token prolog"> ...`
# But `inspect_div.py` showed `... </button><pre ...><code> ...`.
# These are CONTRADICTORY if they refer to the same location.
# `inspect_pre.py` showed `&lt;?xml` after `<code>`.
# `inspect_div.py` showed `&lt;?xml` after `<code>`.
# So they are looking at the SAME code.
# But `inspect_pre.py` showed `pre` at 19970.
# `inspect_div.py` showed `pre` AFTER button.
# So `pre` at 19970 is NOT the one in `inspect_div.py`?
# But `inspect_pre.py` showed `&lt;?xml`.
# `inspect_div.py` showed `&lt;?xml`.
# So there are TWO `pre` tags before `&lt;?xml`?
# <pre ...> (19970)
# ... button ...
# <pre ...> (200xx)
# <code>
# &lt;?xml
# YES! Double pre tags!
# And the button is in between?
# Or inside the first one?

# I need to remove the FIRST pre tag (19970).
# And the button?
# If the button is a toolbar, it should be kept but placed correctly.
# But if I have `code-toolbar` wrapper, maybe I don't need the button (it might be auto-generated by JS on client side?).
# But this is static HTML.
# If I want the button, it should be after pre.
# But if I have double pre, I should remove one.

# I'll check if I can find `<pre ...><div class="code-toolbar">` or similar nesting.
